### PR TITLE
Using polyfill for bind

### PR DESCRIPTION
**Pull request by hemanth**
^ [Reference](https://github.com/hemanth/has/commit/c33777b07ec600a202d08369a6ed1b53ad7185b6#commitcomment-12311980)

### CODE REVIEW

**Comment by tarruda** [comment]
Can you rebase?

**Comment by hemanth** [comment]
Done.

**Comment by tarruda** [comment]
thanks

**Comment by hemanth** [comment]
:+1:

**Comment by fearphage** [comment]
The link in the OP is 404'ing. Anyone remember why this change was needed?

**Comment by ljharb** [comment]
Because older engines don’t have bind.

**Pull request merged**
