### PR TITLE
Remove non-essential files from npm package

### PR DESCRIPTION
**Pull request by jorrit**
An alternative would be to add the following to package.json, which would take care of everything:

```
files: ['src']
```

### CODE REVIEW

**Comment by ljharb** [comment]
This change is fine; using “files” is dangerous and should be avoided.

**Comment by ljharb** [comment]
If you forget to include something in npmignore, the worst possible damage is “your package is a tiny bit larger”. If you forget to include something in “files”, the worst possible damage is “you break every consumer of your package”.

Small package sizes are much much less important than working code.

**Comment by ljharb** [comment]
@jorrit could you check the "allow edits" box in the righthand side of the PR?

**Comment by jorrit** [comment]
@ljharb : done

**Comment by ljharb** [comment]
Published as v1.0.3

**Pull request merged**
